### ISSUE TITLE
Unconsistent output for packages without updates in /updates 

### ISSUE THREAD

**Issue by MichaelMraka** [RedHatInsights/vmaas#197] opened 2018-04-04 13:35 UTC
Output of /udates shows description/summary for some packages without updates but not for others.
E.g.
```
        "telepathy-logger-0.8.0-5.el7.x86_64": {
            "available_updates": [],
            "description": "telepathy-logger is a headless Observer client that logs information\nreceived by the Telepathy framework. It features pluggable\nbackends to log different sorts of messages, in different formats.",
            "summary": "Telepathy framework logging daemon"
        },
        "telepathy-salut-0.8.1-6.el7.x86_64": {
            "available_updates": [],
            "description": "telepathy-salut is a Telepathy connection manager for link-local XMPP.\nNormally, XMPP does not support direct client-to-client interactions,\nsince it requires authentication with a server.  This package makes\nit is possible to establish an XMPP-like communications system on a\nlocal network using zero-configuration networking.",
            "summary": "Link-local XMPP telepathy connection manager"
        },
        "texlive-a4wide-svn20943.0-55.el7.noarch": {},
        "texlive-adjustbox-doc-svn26555.0-38.el7.noarch": {},
        "texlive-ae-doc-svn15878.1.4-38.el7.noarch": {},
```

**Comment by MichaelMraka** [comment] 2018-04-04 14:11
Most likely ```telepathy-logger``` have an update but in a different repo/basearch/releasever so it has been filtered out while the description and summary has been added to the output.

**Comment by ggainey** [comment] 2018-04-10 17:53
Given the discussions w/consumers, I think this needs to return summary/descr for the passed-in NEVRAS, whether those RPMs have updates available or not. Investigating that path.

**Comment by ggainey** [comment] 2018-04-11 18:28
ok - the '"foo" : {}' entries are "packages that don't exist in the DB", the '"available_updates":[]' entries are "packages that are in the DB, and have updates, that are not security updates so we don't care".

Given discussions w/our consumers, I think the current behavior is the besty we can do (esp after #208  was fixed - thanks # @MichaelMraka !)

Closing as "by design"

**Closed by ggainey** 2018-04-11 18:28 UTC
Labels: bug
