### ISSUE TITLE
Underscore in errata name

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#309] opened 2018-06-13 10:10 UTC
I have my testing errata with underscore in name, but I get 404 Not found response.
```zsh
(.vmaas_venv) ➜  vmaas_tests git:(regex_request) ✗ curl http://localhost:8080/api/v1/errata/vmaas_test_1
<html><title>404: Not Found</title><body>404: Not Found</body></html>% 
```
even when I try to find it as `vmaas_`
```zsh
(.vmaas_venv) ➜  vmaas_tests git:(regex_request) ✗ curl http://localhost:8080/api/v1/errata/vmaas_      
<html><title>404: Not Found</title><body>404: Not Found</body></html>%  
```
query for `vmaas` works, so problem is with `'_'`
```zsh
(.vmaas_venv) ➜  vmaas_tests git:(regex_request) ✗ curl http://localhost:8080/api/v1/errata/vmaas | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3909    0  3909    0     0   212k      0 --:--:-- --:--:-- --:--:--  212k
{
    "errata_list": {
        "vmaas_test_1": {
            "synopsis": "VMaaS test errata",
            "summary": "",
            "type": "security",
            "severity": "Critical",
            "description": "VMaaS test errata",
            "solution": "",
            "issued": "2018-04-05T10:50:53+00:00",
            "updated": "2018-04-05T10:50:53+00:00",
            "cve_list": [],
            "package_list": [
                "test-vmaas-0.3-3.noarch"
            ],
            "bugzilla_list": [],
            "reference_list": [],
            "url": "https://access.redhat.com/errata/vmaas_test_1"
        },
        "vmaas_test_2": {
            "synopsis": "VMaaS test errata #2",
            "summary": "",
            "type": "security",
            "severity": "Moderate",
            "description": "VMaaS test errata",
            "solution": "",
            "issued": "2018-04-11T10:50:53+00:00",
            "updated": "2018-04-11T10:50:53+00:00",
            "cve_list": [],
            "package_list": [
                "test-vmaas-2-2.x86_64"
            ],
            "bugzilla_list": [],
            "reference_list": [],
            "url": "https://access.redhat.com/errata/vmaas_test_2"
        },
...
    },
    "page": 1,
    "page_size": 5000,
    "pages": 1
}

```

**Comment by grinrag** [comment] 2018-06-13 12:43
@psegedy It's expected behavior, we specify which characters are allowed in an erratum name. Look at the line:
https://github.com/RedHatInsights/vmaas/blob/bf6af34fc421a7e7a386c1cc06d671d4b99f9bc0/webapp/app.py#L815

**Comment by grinrag** [comment] 2018-06-13 12:44
So, I'm closing this as **NOT A BUG**. But if you have ever seen an erratum released by Red Hat which contains `_` in the name, please reopen this bug.

**Closed by grinrag** 2018-06-13 12:44 UTC
